chore: add history TTL property panel entry
camunda/linting pull request #66
Opened 2023-07-17 09:38 UTC by marstamm

related to https://github.com/camunda/camunda-modeler/issues/3712

![Recording 2023-07-17 at 11 36 03](https://github.com/camunda/linting/assets/21984219/c138caf7-0ed2-4b28-ad01-9646ce7c3ed8)

2023-07-17 13:50 UTC, philippfromme commented
Now I remember why we did prevent selecting the root element. It's not supposed to be selected. No selected element leads to the root element being displayed in the properties panel.

![brave_ys0j7sw1P8](https://github.com/camunda/linting/assets/7633572/ef66cd3e-6758-443b-8785-3b82093fca6f)

2023-07-17 13:51 UTC, marstamm commented
🤯

Let's select none then 😄

2023-07-17 14:08 UTC, marstamm commented
adjusted via [a53aa92](https://github.com/camunda/linting/pull/66/commits/a53aa927ba7e63e16e4493239023dfd05ba79233)

2023-07-17 14:27 UTC, philippfromme requested changes
👀

2023-07-17 14:28 UTC, philippfromme commented on lib/modeler/Linting.js
> +      this._selection.select(null);
Cf. https://github.com/bpmn-io/diagram-js/blob/develop/test/spec/features/selection/SelectionSpec.js#L127

2023-07-17 14:29 UTC, marstamm commented on lib/modeler/Linting.js
> +      this._selection.select(null);
Is it? In the selection module, we also use `null`: 
https://github.com/bpmn-io/diagram-js/blob/master/lib/features/selection/Selection.js#L36

2023-07-18 07:58 UTC, marstamm commented on lib/modeler/Linting.js
> +      this._selection.select(null);
Adjusted and removed the explicit `null` with [43e7520](https://github.com/camunda/linting/pull/66/commits/43e7520d8298d60103575e6b4d7737b67251c71c)

2023-07-20 12:16 UTC, nikku commented
@philippfromme This is waiting for your review.

2023-07-20 12:48 UTC, philippfromme commented on lib/modeler/Linting.js
> +      this._selection.select(null);
Okay, `select(null)` will actually result in the selection being `[]` as well but it's superfluous.

2023-07-20 12:49 UTC, merged